stages:
  - test
  - build
  - deploy

test-poly:
  stage: test
  image: clojure:latest
  script:
    - clojure -M:poly test
  artifacts:
    when: always
    paths:
      - "target/junit.xml"
    reports:
      - "target/junit.xml"

test-cms:
  stage: test
  image: rjsheperd/clojure-bb-bun-chrome:latest
  needs: ["test-poly"]
  script:
    - cd projects/behave_cms
    - bun add --global phantomjs
    - bun install
    - bb test
  artifacts:
    when: always
    paths:
      - "projects/behave_cms/target/results.xml"
    paths:
      - "projects/behave_cms/target/results.xml"

test-app:
  stage: test
  image: rjsheperd/clojure-bb-bun-chrome:latest
  needs: ["test-poly"]
  script:
    - cd projects/behave
    - bun add --global phantomjs
    - bun install
    - bb test
  artifacts:
    when: always
    paths:
      - "projects/behave/target/results.xml"
    paths:
      - "projects/behave/target/results.xml"

build-cms:
  stage: build
  image: rjsheperd/clojure-bb-bun:latest
  needs: ["test-cms"]
  script:
    - cd projects/behave_cms
    - bun install --production
    - bb build-js
    - bb uber
  artifacts:
    paths:
      - "projects/behave_cms/target/*.jar"

build-app:
  stage: build
  image: rjsheperd/clojure-bb-bun:latest
  needs: ["test-app"]
  script:
    - cd projects/behave
    - bun install --production
    - bb build-js
    - bb uber
  artifacts:
    paths:
      - "projects/behave/target/*.jar"

# test-connect-cms:
#   stage: deploy
#   script:
#     - apk add --no-cache openssh
# 
#     ##
#     ## Run ssh-agent (inside the build environment)
#     ##
#     - eval $(ssh-agent -s)
# 
#     ##
#     ## Give the right permissions, otherwise ssh-add will refuse to add files
#     ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
#     ##
#     - echo $SSH_PRIVATE_KEY
#     - chmod 400 "$SSH_PRIVATE_KEY"
#     - ssh-add "$SSH_PRIVATE_KEY"
# 
#     ##
#     ## Create the SSH directory and give it the right permissions
#     ##
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh sig-app@10.1.30.129 "date"
