build-wasm:
  image: nixos/nix:latest
  stage: build
  cache:
    - key:
        files:
          - behave-lib/shell.nix
      paths:
        - /nix/store

    - key: cache-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - cache-$CI_DEFAULT_BRANCH
        - cache-default
      paths:
        - /nix/store
        - .em_cache
  script:
    # Build WASM
    - cd behave-lib
    - echo Building WASM with Nix...
    - nix-shell --run 'make install'

    # Push back upstream
    # - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@$PROJECT_GIT_URL
    # - git config user.email "ci-bot@sig-gis.com"
    # - git config user.name "ci-bot"
    # - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@PROJECT_GIT_URL
    # - git add projects/behave/resources/
    # - git commit -m "Update WASM"
    # - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again


