(ns behave.lib.mortality
  (:require [behave.lib.species-master-table :as species-master-table]))

;; Auto-generated by hatchet 🪓
(defn init
  ([]
   (init (species-master-table/init)))
  ([speciesMasterTable]
   (js/Module.SIGMortality. speciesMasterTable)))

(defn initializeMembers [self]
  (.initializeMembers self))

(defn calculateMortality [self probablityUnits]
  (.calculateMortality self probablityUnits))

(defn calculateMortalityAllDirections [self probablityUnits]
  (.calculateMortalityAllDirections self probablityUnits))

(defn checkIsInRegionAtSpeciesTableIndex [self index region]
  (.checkIsInRegionAtSpeciesTableIndex self index region))

(defn checkIsInRegionFromSpeciesCode [self speciesCode region]
  (.checkIsInRegionFromSpeciesCode self speciesCode region))

(defn getBarkEquationNumberAtSpeciesTableIndex [self index]
  (.getBarkEquationNumberAtSpeciesTableIndex self index))

(defn getBarkEquationNumberFromSpeciesCode [self speciesCode]
  (.getBarkEquationNumberFromSpeciesCode self speciesCode))

(defn getBarkThickness [self barkThicknessUnits]
  (.getBarkThickness self barkThicknessUnits))

(defn getBasalAreaKillled [self]
  (.getBasalAreaKillled self))

(defn getBasalAreaPostfire [self]
  (.getBasalAreaPostfire self))

(defn getBasalAreaPrefire [self]
  (.getBasalAreaPrefire self))

(defn getBeetleDamage [self]
  (.getBeetleDamage self))

(defn getBoleCharHeight [self boleCharHeightUnits]
  (.getBoleCharHeight self boleCharHeightUnits))

(defn getCalculatedScorchHeight [self scorchHeightUnits]
  (.getCalculatedScorchHeight self scorchHeightUnits))

(defn getCambiumKillRating [self]
  (.getCambiumKillRating self))

(defn getCommonNameAtSpeciesTableIndex [self index]
  (.getCommonNameAtSpeciesTableIndex self index))

(defn getCommonNameFromSpeciesCode [self speciesCode]
  (.getCommonNameFromSpeciesCode self speciesCode))

(defn getCrownCoefficientCodeAtSpeciesTableIndex [self index]
  (.getCrownCoefficientCodeAtSpeciesTableIndex self index))

(defn getCrownCoefficientCodeFromSpeciesCode [self speciesCode]
  (.getCrownCoefficientCodeFromSpeciesCode self speciesCode))

(defn getCrownDamage [self]
  (.getCrownDamage self))

(defn getCrownDamageEquationCode [self]
  (.getCrownDamageEquationCode self))

(defn getCrownDamageEquationCodeAtSpeciesTableIndex [self index]
  (.getCrownDamageEquationCodeAtSpeciesTableIndex self index))

(defn getCrownDamageEquationCodeFromSpeciesCode [self speciesCode]
  (.getCrownDamageEquationCodeFromSpeciesCode self speciesCode))

(defn getCrownDamageType [self]
  (.getCrownDamageType self))

(defn getCrownRatio [self]
  (.getCrownRatio self))

(defn getCrownScorchOrBoleCharEquationNumber [self]
  (.getCrownScorchOrBoleCharEquationNumber self))

(defn getDBH [self diameterUnits]
  (.getDBH self diameterUnits))

(defn getEquationType [self]
  (.getEquationType self))

(defn getEquationTypeAtSpeciesTableIndex [self index]
  (.getEquationTypeAtSpeciesTableIndex self index))

(defn getEquationTypeFromSpeciesCode [self speciesCode]
  (.getEquationTypeFromSpeciesCode self speciesCode))

(defn getFireSeverity [self]
  (.getFireSeverity self))

(defn getFlameLengthOrScorchHeightSwitch [self]
  (.getFlameLengthOrScorchHeightSwitch self))

(defn getFlameLengthOrScorchHeightValue [self flameLengthOrScorchHeightUnits]
  (.getFlameLengthOrScorchHeightValue self flameLengthOrScorchHeightUnits))

(defn getFlameLength [self flameLengthUnits]
  (.setFlameLength self flameLengthUnits))

(defn getScorchHeight [self scorchHeightUnits]
  (.getScorchHeight self scorchHeightUnits))

(defn getScorchHeightBacking [self scorchHeightUnits]
  (.getScorchHeightBacking self scorchHeightUnits))

(defn getScorchHeightFlanking [self scorchHeightUnits]
  (.getScorchHeightFlanking self scorchHeightUnits))

(defn getKilledTrees [self]
  (.getKilledTrees self))

(defn getMortalityEquationNumberAtSpeciesTableIndex [self index]
  (.getMortalityEquationNumberAtSpeciesTableIndex self index))

(defn getMortalityEquationNumberFromSpeciesCode [self speciesCode]
  (.getMortalityEquationNumberFromSpeciesCode self speciesCode))

(defn getNumberOfRecordsInSpeciesTable [self]
  (.getNumberOfRecordsInSpeciesTable self))

(defn getProbabilityOfMortality [self probabilityUnits]
  (.getProbabilityOfMortality self probabilityUnits))

(defn getProbabilityOfMortalityBacking [self probabilityUnits]
  (.getProbabilityOfMortalityBacking self probabilityUnits))

(defn getProbabilityOfMortalityFlanking [self probabilityUnits]
  (.getProbabilityOfMortalityFlanking self probabilityUnits))

(defn getRegion [self]
  (.getRegion self))

(defn getRequiredFieldVector [self]
  (.getRequiredFieldVector self))

(defn getScientificNameAtSpeciesTableIndex [self index]
  (.getScientificNameAtSpeciesTableIndex self index))

(defn getScientificNameFromSpeciesCode [self speciesCode]
  (.getScientificNameFromSpeciesCode self speciesCode))

(defn getSpeciesCode [self]
  (.getSpeciesCode self))

(defn getSpeciesCodeAtSpeciesTableIndex [self index]
  (.getSpeciesCodeAtSpeciesTableIndex self index))

(defn getSpeciesRecordAtIndex [self index]
  (.getSpeciesRecordAtIndex self index))

(defn getSpeciesRecordBySpeciesCodeAndEquationType [self speciesCode equationType]
  (.getSpeciesRecordBySpeciesCodeAndEquationType self speciesCode equationType))

(defn getSpeciesRecordVectorForRegion [self region]
  (.getSpeciesRecordVectorForRegion self region))

(defn getSpeciesRecordVectorForRegionAndEquationType [self region equationType]
  (.getSpeciesRecordVectorForRegionAndEquationType self region equationType))

(defn getSpeciesTableIndexFromSpeciesCode [self speciesNameCode]
  (.getSpeciesTableIndexFromSpeciesCode self speciesNameCode))

(defn getSpeciesTableIndexFromSpeciesCodeAndEquationType [self speciesNameCode equationType]
  (.getSpeciesTableIndexFromSpeciesCodeAndEquationType self speciesNameCode equationType))

(defn getTotalPrefireTrees [self]
  (.getTotalPrefireTrees self))

(defn getTreeCrownLengthScorched [self lengthUnits]
  (.getTreeCrownLengthScorched self lengthUnits))

(defn getTreeCrownLengthScorchedBacking [self lengthUnits]
  (.getTreeCrownLengthScorchedBacking self lengthUnits))

(defn getTreeCrownLengthScorchedFlanking [self lengthUnits]
  (.getTreeCrownLengthScorchedFlanking self lengthUnits))

(defn getTreeCrownVolumeScorched [self mortalityRateUnits]
  (.getTreeCrownVolumeScorched self mortalityRateUnits))

(defn getTreeCrownVolumeScorchedBacking [self mortalityRateUnits]
  (.getTreeCrownVolumeScorchedBacking self mortalityRateUnits))

(defn getTreeCrownVolumeScorchedFlanking [self mortalityRateUnits]
  (.getTreeCrownVolumeScorchedFlanking self mortalityRateUnits))

(defn getTreeDensityPerUnitArea [self areaUnits]
  (.getTreeDensityPerUnitArea self areaUnits))

(defn getTreeHeight [self treeHeightUnits]
  (.getTreeHeight self treeHeightUnits))

(defn operator= [self rhs]
  (.operator= self rhs))

(defn postfireCanopyCover [self]
  (.postfireCanopyCover self))

(defn prefireCanopyCover [self]
  (.prefireCanopyCover self))

(defn setAirTemperature [self airTemperature temperatureUnits]
  (.setAirTemperature self airTemperature temperatureUnits))

(defn setBeetleDamage [self beetleDamage]
  (.setBeetleDamage self beetleDamage))

(defn setBoleCharHeight [self boleCharHeight boleCharHeightUnits]
  (.setBoleCharHeight self boleCharHeight boleCharHeightUnits))

(defn setCambiumKillRating [self cambiumKillRating]
  (.setCambiumKillRating self cambiumKillRating))

(defn setCrownDamage [self crownDamage]
  (.setCrownDamage self crownDamage))

(defn setCrownRatio [self crownRatio]
  (.setCrownRatio self crownRatio))

(defn setDBH [self dbh diameterUnits]
  (.setDBH self dbh diameterUnits))

(defn setEquationType [self equationType]
  (.setEquationType self equationType))

(defn setFireSeverity [self fireSeverity]
  (.setFireSeverity self fireSeverity))

(defn setFirelineIntensity [self firelineIntensity firelineIntensityUnits]
  (.setFirelineIntensity self firelineIntensity firelineIntensityUnits))

(defn setFlameLengthOrScorchHeightSwitch [self flameLengthOrScorchHeightSwitch]
  (.setFlameLengthOrScorchHeightSwitch self flameLengthOrScorchHeightSwitch))

(defn setFlameLengthOrScorchHeightValue [self flameLengthOrScorchHeightValue flameLengthOrScorchHeightUnits]
  (.setFlameLengthOrScorchHeightValue self flameLengthOrScorchHeightValue flameLengthOrScorchHeightUnits))

(defn setFlameLength [self flameLength flameLengthUnits]
  (.setFlameLength self flameLength flameLengthUnits))

(defn setScorchHeight [self scorchHeight scorchHeightUnits]
  (.setScorchHeight self scorchHeight scorchHeightUnits))

(defn setMidFlameWindSpeed [self midFlameWindSpeed windSpeedUnits]
  (.setMidFlameWindSpeed self midFlameWindSpeed windSpeedUnits))

(defn setRegion [self region]
  (.setRegion self region))

(defn setSpeciesCode [self speciesCode]
  (.setSpeciesCode self speciesCode))

(defn setSurfaceFireScorchHeight [self value lengthUnits]
  (.setSurfaceFireScorchHeight self value lengthUnits))

(defn setSurfaceFireFlameLength [self value lengthUnits]
  (.setSurfaceFireFlameLength self value lengthUnits))

(defn setSurfaceFireFlameLengthBacking [self value lengthUnits]
  (.setSurfaceFireFlameLengthBacking self value lengthUnits))

(defn setSurfaceFireFlameLengthFlanking [self value lengthUnits]
  (.setSurfaceFireFlameLengthFlanking self value lengthUnits))

(defn setSurfaceFireFirelineIntensity [self value firelineIntensityUnits]
  (.setSurfaceFireFirelineIntensity self value firelineIntensityUnits))

(defn setSurfaceFireFirelineIntensityBacking [self value firelineIntensityUnits]
  (.setSurfaceFireFirelineIntensityBacking self value firelineIntensityUnits))

(defn setSurfaceFireFirelineIntensityFlanking [self value firelineIntensityUnits]
  (.setSurfaceFireFirelineIntensityFlanking self value firelineIntensityUnits))

(defn setTreeDensityPerUnitArea [self numberOfTrees areaUnits]
  (.setTreeDensityPerUnitArea self numberOfTrees areaUnits))

(defn setTreeHeight [self treeHeight treeHeightUnits]
  (.setTreeHeight self treeHeight treeHeightUnits))

(defn setUserProvidedWindAdjustmentFactor [self userProvidedWindAdjustmentFactor]
  (.setUserProvidedWindAdjustmentFactor self userProvidedWindAdjustmentFactor))

(defn setWindHeightInputMode [self windHeightInputMode]
  (.setWindHeightInputMode self windHeightInputMode))

(defn setWindSpeed [self windSpeed windSpeedUnits]
  (.setWindSpeed self windSpeed windSpeedUnits))

(defn setWindSpeedAndWindHeightInputMode [self windwindSpeed windSpeedUnits windHeightInputMode userProvidedWindAdjustmentFactor]
  (.setWindSpeedAndWindHeightInputMode self windwindSpeed windSpeedUnits windHeightInputMode userProvidedWindAdjustmentFactor))

(defn updateInputsForSpeciesCodeAndEquationType [self speciesCode equationType]
  (.updateInputsForSpeciesCodeAndEquationType self speciesCode equationType))
